config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :albums do
    resources :photos
  end




  root 'albums#index'

  get "/login" => 'session#new', as: :login
 post "/login" => 'session#create'
 delete "/logout" => 'session#destroy', as: :logout
 get '/about' => 'albums#about', as: :about

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :photos, dependent: :destroy
  validates :title, presence: true

  def thumbnail
    if photos.first
      photos.first.file.url(:thumb)
    else
      'https://unsplash.it/g/100/100'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord

belongs_to :album

validates :caption, presence: true


end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :albums, dependent: :destroy



  

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

before_action :require_user, only: [:new, :create]
before_action :redirect_if_logged_out, only: [:index]
before_action :is_owner, only: [:destroy]

def redirect_if_logged_out
  redirect_to about_path if current_user.blank?
end

def about

end

def index
  @albums = Album.page(params[:page])
end

def show
  @album = Album.find(params[:id]).photos.all
end

def new
  @user = User.find(params[:user_id])
  @album = Album.new
end

def create
  @album = current_user.album.new(album_params)
  if @album.save
    redirect_to @album
  else
    render :new
  end
end

  private

  def album_params
    params.require(:album).permit(:title)
  end

  def is_owner
   @album = current_user.album.find_by(id: params[:id])
   unless @album && @album.user == current_user
     flash[:danger] = "You can't do that."
     redirect_to :root
   end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user


   private

   def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end


   def require_user
     unless current_user
       flash[:warning] = "You need to login, first."
       redirect_to :login
     end
   end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :require_user, only: [:new, :create, :destroy]
  before_action :is_owner, only: [:destroy]

  def show
    @photo = @album.photos.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = @album.photos.new(photo_params)
    if @photo.save
      redirect_to @album
    else
      render :new
    end
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :file)
  end

  def is_owner
   @photo = current_user.photo.find_by(id: params[:id])
   unless @photo && @photo.user == current_user
     flash[:danger] = "You can't do that."
     redirect_to :root
   end
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:primary] = "Welcome #{@user.username}!"
      redirect_to :root
    else
      flash[:danger] = 'Invalid username or password. Please try Again.'
      redirect_to :login
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user, only: [:show]

def index
  @users = User.all
end

def show
  @albums = @user.albums
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    UserMailer.signup(@user).deliver
    session[:user_id] = @user.id
    redirect_to user_path
  else
      render :new
  end
end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id]) if params[:id]
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/about.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Welcome to Galleria!</h1>
                        <h3>Yet another site to dump the pictures of yourself that no one really looks at except Grandma...and we'd really rather she didn't... </h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="https://twitter.com/viralartistic" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                            </li>
                            <li>
                                <a href="https://github.com/davmckin/galleria" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                            </li>
                            <li>
                                <%= link_to "Signup!", new_user_path, class: "btn btn-default btn-lg" %>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Create An Online Persona</h2>
                    <p class="lead">Give the impression you have some formal art training, or that you have any idea what art is. It's the internet. No one knows who you are, kind of.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="gallery.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">More Sharing Options</h2>
                    <p class="lead">Instead of inviting your work friends over to see your mediocre vacation photos, fill up their email inbox with links to your favorite pics that barely have your thumb covering the lense. </p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="lastone.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">You Could Receive Comments!</h2>
                    <p class="lead">Lol. No one is going to comment. Let's be real. No one has even heard of this site, and your email will most definitely mark this as spam.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="moreart.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Connect to Learn More About Our Company:</h2>
                </div>
                <div class="col-lg-6">
                  <ul class="list-inline intro-social-buttons">
                      <li>
                          <a href="https://twitter.com/viralartistic" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                      </li>
                      <li>
                          <a href="https://github.com/davmckin/galleria" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                      </li>
                      <li>
                          <%= link_to "Signup!", new_user_path, class: "btn btn-default btn-lg" %>

                      </li>
                  </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">

                    <p class="copyright text-muted small">Copyright &copy; Galleria 2017. Some Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/albums/index.html.erb
<div class="container">

<!-- Page Header -->
<div class="row">
 <div class="col-lg-12">
     <h1 class="page-header">Albums

     </h1>
 </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
 <div class="col-md-6 portfolio-item">
     <a href="#">
         <img class="img-responsive" src="http://placehold.it/700x400" alt="">
     </a>
     <h3>
         <a href="#">Album Title will go here</a>
     </h3>
 </div>
 <div class="col-md-6 portfolio-item">
     <a href="#">
         <img class="img-responsive" class="img-thumbnail" src="http://placehold.it/700x400" alt="" width="700" height="400">
     </a>
     <h3>
         <a href="#">Album Title will go here</a>
     </h3>
 </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
 <div class="col-md-6 portfolio-item">
     <a href="#">
       <img class="img-responsive" class="img-thumbnail" src="http://placehold.it/700x400" alt="" width="700" height="400">
     </a>
     <h3>
         <a href="#">Album Title will go here</a>
     </h3>
 </div>
 <div class="col-md-6 portfolio-item">
     <a href="#">
       <img class="img-responsive" class="img-thumbnail" src="http://placehold.it/700x400" alt="" width="700" height="400">
     </a>
     <h3>
         <a href="#">Album Title will go here</a>

     </h3>
 </div>
</div>
<!-- /.row -->

<!-- Projects Row -->
<div class="row">
 <div class="col-md-6 portfolio-item">
     <a href="#">
       <img class="img-responsive" class="img-thumbnail" src="http://placehold.it/700x400" alt="" width="700" height="400">
     </a>
     <h3>
         <a href="#">Album Title will go here</a>
     </h3>
 </div>
 <div class="col-md-6 portfolio-item">
     <a href="#">
       <img class="img-responsive" class="img-thumbnail" src="http://placehold.it/700x400" alt="" width="700" height="400">
     </a>
     <h3>
         <a href="#">Album Title will go here</a>
     </h3>
 </div>
</div>
<!-- /.row -->

<hr>

<!-- Pagination -->
<div class="row text-center">
 <div class="col-lg-12">
     <ul class="pagination">
         <li>
             <a href="#">&laquo;</a>
         </li>
         <li class="active">
             <a href="#">1</a>
         </li>
         <li>
             <a href="#">2</a>
         </li>
         <li>
             <a href="#">3</a>
         </li>
         <li>
             <a href="#">4</a>
         </li>
         <li>
             <a href="#">5</a>
         </li>
         <li>
             <a href="#">&raquo;</a>
         </li>
     </ul>
 </div>
</div>
<!-- /.row -->

<hr>

<!-- Footer -->
<footer>
 <div class="row">
     <div class="col-lg-12">
         <p>Copyright &copy; Galleria 2017</p>
     </div>
 </div>
 <!-- /.row -->
</footer>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

    <html lang="en">

        <head>
            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
            <%= csrf_meta_tags %>

            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="description" content="">
            <meta name="author" content="">

            <title>Galleria</title>

            <!-- Bootstrap Core CSS -->
            <link href="css/bootstrap.min.css" rel="stylesheet">

            <!-- Custom CSS -->
            <link href="css/2-col-portfolio.css" rel="stylesheet">

        </head>

        <body>

            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>
                                <%= link_to 'Galleria', root_path %>
                            </li>
                            <% if current_user %>
                            <li><%= link_to "Logout!", logout_path, method: :delete, class: "btn" %></li>
                            <li><%= link_to "Add Photo!", new_album_photo_path(current_user.albums), class: "btn" %></li>
                            <li><%= link_to "About!", about_path, class: "btn" %></li>
                        <% else %>
                            <li><%= link_to "Login!", login_path, class: "btn" %></li>
                            <li><%= link_to "Signup!", new_user_path, class: "btn" %></li>
                            <li><%= link_to "About!", about_path, class: "btn" %></li>
                            <% end%>

                        </ul>

                    </div>

                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container -->
            </nav>
           </body>


</html>
<%= yield %>
</html>

app/views/photos/new.html.erb
<h1>Add Your Photo!</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for [@photo, @album], html: {class: "form-horizontal"} do |f| %>

        <%= f.input :file %>
        <%= f.input :caption %>
        <%= f.button :submit %>

      <% end %>
    </div>
  </div>
</div>

app/views/session/new.html.erb
<h1>Log In!</h1>

<%= simple_form_for :session do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.button :submit, "Log In!", class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>

  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>

<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="col-md-3 col-sm-6">
    <%= link_to user.username, class: "btn btn-default" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render "form" %>